
import { Book } from './types';

const SAMPLE_PDF = 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf';
const START_WITH_WHY_LINK = 'https://upfiles.com/AJZC';
const ATOMIC_HABITS_LINK = 'https://www.mediafire.com/file/l50l9gjj9nqz7a2/%2528mktbtypdf.com%2529-%25D8%25B9%25D8%25AF%25D8%25A7%25D8%25AD-%25D8%25B0%25D8%25B1%25D9%258A%25D8%25A9.pdf/file';
const ANTICHRISTOS_LINK = 'https://upfiles.com/C1M6G8nL';
const THE_5AM_CLUB_LINK = 'https://upfiles.com/JOKL';
const HEAR_WHISPER_LINK = 'https://upfiles.com/hckrOE';
const FORTY_RULES_LOVE_LINK = 'https://upfiles.com/I7RK393T';

export const INITIAL_BOOKS: Book[] = [
  {
    id: 'start-with-why',
    title: 'ابدأ بلماذا (Start with Why)',
    author: 'سايمون سينك',
    shortDescription: 'كيف يلهم القادة العظام الجميع لاتخاذ إجراءات من خلال البدء بـ "لماذا".',
    description: 'كتاب "ابدأ بلماذا" للكاتب والمحاضر الملهم سايمون سينك هو ثورة في عالم القيادة والتسويق. يشرح سينك من خلال مفهوم "الدائرة الذهبية" لماذا تنجح بعض الشركات والأشخاص في الإلهام والابتكار بينما يفشل الآخرون.',
    coverImage: 'https://images.unsplash.com/photo-1553484771-371a605b060b?auto=format&fit=crop&q=80&w=400&h=600',
    downloadUrl: START_WITH_WHY_LINK,
    category: 'إدارة أعمال',
    views: 18000,
    downloads: 6200,
    trending: true,
    price: 'مجاني',
    format: 'PDF',
    pagesCount: 324,
    rating: 4.8,
    ratingCount: 21030,
    seoKeywords: ['ابدأ بلماذا', 'سايمون سينك', 'Start with Why بالعربي'],
    metaDescription: 'تحميل كتاب ابدأ بلماذا لسايمون سينك PDF.'
  },
  {
    id: 'antichristos',
    title: 'أنتيخريستوس',
    author: 'أحمد خالد مصطفى',
    shortDescription: 'رواية تمزج بين الواقع والخيال التاريخي حول السحر والجن والمؤامرات العالمية.',
    description: 'رواية "أنتيخريستوس" للدكتور أحمد خالد مصطفى هي واحدة من أكثر الروايات إثارة للجدل في الوطن العربي. تأخذك الرواية في رحلة عبر الزمن لتعرض أحداثاً تاريخية غامضة.',
    coverImage: 'https://images.unsplash.com/photo-1514593214839-ce18510cd85a?auto=format&fit=crop&q=80&w=400&h=600',
    downloadUrl: ANTICHRISTOS_LINK,
    category: 'روايات',
    views: 68000,
    downloads: 32000,
    trending: true,
    price: 'مجاني',
    format: 'PDF',
    pagesCount: 450,
    rating: 4.5,
    ratingCount: 12000,
    seoKeywords: ['أنتيخريستوس', 'تحميل أنتيخريستوس pdf'],
    metaDescription: 'تحميل رواية أنتيخريستوس PDF مجاناً.'
  },
  {
    id: 'trending-1',
    title: 'العادات الذرية (Atomic Habits)',
    author: 'جيمس كلير',
    shortDescription: 'دليل عملي لبناء عادات جيدة والتخلص من العادات السيئة لتحقيق نتائج مذهلة.',
    description: 'كتاب العادات الذرية لجيمس كلير هو المرجع الأهم عالمياً في تطوير الذات وإدارة السلوك. يشرح الكتاب كيف أن التغييرات البسيطة جداً يمكن أن تؤدي إلى نتائج تراكمية هائلة.',
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=400&h=600',
    downloadUrl: ATOMIC_HABITS_LINK,
    category: 'تطوير الذات',
    views: 95200,
    downloads: 41850,
    trending: true,
    price: 'مجاني',
    format: 'PDF',
    pagesCount: 280,
    rating: 4.9,
    ratingCount: 15400,
    seoKeywords: ['العادات الذرية', 'تحميل العادات الذرية pdf'],
    metaDescription: 'تحميل كتاب العادات الذرية لجيمس كلير مجاناً.'
  },
  {
    id: '5am-club',
    title: 'نادي الخامسة صباحاً (The 5 AM Club)',
    author: 'روبن شارما',
    shortDescription: 'امتلك صباحك، وارتقِ بحياتك: الدليل العملي لتحقيق الإنتاجية القصوى.',
    description: 'كتاب "نادي الخامسة صباحاً" للمتحدث العالمي روبن شارما يقدم استراتيجية عملية لتقسيم الساعة الأولى من يومك بين الرياضة، التأمل، والتعلم.',
    coverImage: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=400&h=600',
    downloadUrl: THE_5AM_CLUB_LINK,
    category: 'تطوير الذات',
    views: 12500,
    downloads: 5400,
    trending: true,
    price: 'مجاني',
    format: 'PDF',
    pagesCount: 312,
    rating: 4.7,
    ratingCount: 8900,
    seoKeywords: ['نادي الخامسة صباحا', 'روبن شارما'],
    metaDescription: 'تحميل كتاب نادي الخامسة صباحاً لروبن شارما PDF.'
  },
  {
    id: 'ikigai',
    title: 'إيكيجاي (Ikigai)',
    author: 'هيكتور غارسيا وفرانسيس ميراليس',
    shortDescription: 'أسرار اليابان لحياة طويلة وسعيدة من خلال إيجاد سبب وجودك.',
    description: 'كتاب "إيكيجاي" يقدم لك الإجابة عن سر الحياة الطويلة والسعيدة لسكان جزيرة أوكيناوا اليابانية.',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400&h=600',
    downloadUrl: SAMPLE_PDF,
    category: 'تطوير الذات',
    views: 15000,
    downloads: 7100,
    trending: true,
    price: 'مجاني',
    format: 'PDF',
    pagesCount: 208,
    rating: 4.6,
    ratingCount: 5200,
    seoKeywords: ['إيكيجاي', 'Ikigai بالعربي'],
    metaDescription: 'تحميل كتاب إيكيجاي PDF.'
  },
  {
    id: 'hear-whisper',
    title: 'يسمعون حسيسها',
    author: 'أيمن عتوم',
    shortDescription: 'رواية أدبية مستوحاة من أحداث حقيقية عن الصبر والإرادة في سجون تدمر.',
    description: 'رواية "يسمعون حسيسها" للشاعر والروائي الأردني أيمن عتوم، تسطر ملحمة إنسانية عن المعاناة والحرية.',
    coverImage: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400&h=600',
    downloadUrl: HEAR_WHISPER_LINK,
    category: 'أدب',
    views: 42000,
    downloads: 18000,
    trending: false,
    price: 'مجاني',
    format: 'PDF',
    pagesCount: 365,
    rating: 4.8,
    ratingCount: 14500,
    seoKeywords: ['يسمعون حسيسها', 'أيمن عتوم'],
    metaDescription: 'تحميل رواية يسمعون حسيسها لأيمن عتوم PDF.'
  },
  {
    id: 'forty-rules-love',
    title: 'قواعد العشق الأربعون',
    author: 'إليف شافاق',
    shortDescription: 'رواية عن جلال الدين الرومي وشمس التبريزي ورحلة البحث عن الحب الإلهي.',
    description: 'رواية "قواعد العشق الأربعون" للروائية التركية إليف شافاق، هي تحفة فنية تربط بين الماضي والحاضر.',
    coverImage: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&q=80&w=400&h=600',
    downloadUrl: FORTY_RULES_LOVE_LINK,
    category: 'روايات',
    views: 85000,
    downloads: 41000,
    trending: true,
    price: 'مجاني',
    format: 'PDF',
    pagesCount: 512,
    rating: 4.4,
    ratingCount: 32000,
    seoKeywords: ['قواعد العشق الأربعون', 'إليف شافاق'],
    metaDescription: 'تحميل رواية قواعد العشق الأربعون PDF.'
  },
  {
    id: 'pistachio-theory',
    title: 'نظرية الفستق',
    author: 'فهد عامر الأحمدي',
    shortDescription: 'كتاب سيغير طريقة تفكيرك وحكمك على الأشياء عبر مجموعة مقالات في تطوير الذات.',
    description: 'يعد كتاب "نظرية الفستق" للكاتب السعودي فهد عامر الأحمدي واحداً من أكثر الكتب مبيعاً في تطوير الذات.',
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=400&h=600',
    downloadUrl: SAMPLE_PDF,
    category: 'تطوير الذات',
    views: 22500,
    downloads: 9800,
    trending: false,
    price: 'مجاني',
    format: 'PDF',
    pagesCount: 338,
    rating: 4.3,
    ratingCount: 18000,
    seoKeywords: ['نظرية الفستق', 'فهد عامر الأحمدي'],
    metaDescription: 'تحميل كتاب نظرية الفستق للفهد عامر الأحمدي مجاناً.'
  },
  {
    id: 'because-you-are-allah',
    title: 'لأنك الله: رحلة إلى السماء السابعة',
    author: 'علي بن جابر الفيفي',
    shortDescription: 'كلمات في حب الله تقربك من أسمائه الحسنى وتلمس روحك في أوقات الشدة.',
    description: 'كتاب "لأنك الله" هو رحلة روحية إيمانية هادئة تأخذك في عمق معاني أسماء الله الحسنى.',
    coverImage: 'https://images.unsplash.com/photo-1585779034823-7e9ac8faec70?auto=format&fit=crop&q=80&w=400&h=600',
    downloadUrl: SAMPLE_PDF,
    category: 'أدب',
    views: 31000,
    downloads: 15400,
    trending: false,
    price: 'مجاني',
    format: 'PDF',
    pagesCount: 192,
    rating: 4.9,
    ratingCount: 25000,
    seoKeywords: ['لأنك الله', 'علي بن جابر الفيفي'],
    metaDescription: 'تحميل كتاب لأنك الله PDF لعلي الفيفي.'
  },
  {
    id: 'subtle-art',
    title: 'فن اللامبالاة',
    author: 'مارك مانسون',
    shortDescription: 'دليل غير تقليدي لعيش حياة تخالف المألوف وتركز على ما يهم حقاً.',
    description: 'في كتاب "فن اللامبالاة"، يكسر مارك مانسون القواعد التقليدية للتنمية البشرية ليقدم رؤية واقعية للحياة.',
    coverImage: 'https://images.unsplash.com/photo-1589829025471-3303d193bca4?auto=format&fit=crop&q=80&w=400&h=600',
    downloadUrl: SAMPLE_PDF,
    category: 'تطوير الذات',
    views: 45000,
    downloads: 21000,
    trending: true,
    price: 'مجاني',
    format: 'PDF',
    pagesCount: 272,
    rating: 4.1,
    ratingCount: 56000,
    seoKeywords: ['فن اللامبالاة', 'مارك مانسون'],
    metaDescription: 'تحميل كتاب فن اللامبالاة لمارك مانسون PDF.'
  },
  {
    id: 'zikola-land',
    title: 'أرض زيكولا',
    author: 'عمرو عبد الحميد',
    shortDescription: 'رواية خيالية تأخذك إلى عالم لا يُتعامل فيه بالمال، بل بوحدات الذكاء.',
    description: 'رواية "أرض زيكولا" هي واحدة من أشهر الروايات الفانتازيا المصرية التي حققت انتشاراً واسعاً.',
    coverImage: 'https://images.unsplash.com/photo-1531988041414-d05061034346?auto=format&fit=crop&w=400&h=600',
    downloadUrl: SAMPLE_PDF,
    category: 'روايات',
    views: 55000,
    downloads: 28000,
    trending: false,
    price: 'مجاني',
    format: 'PDF',
    pagesCount: 288,
    rating: 4.7,
    ratingCount: 42000,
    seoKeywords: ['أرض زيكولا', 'عمرو عبد الحميد'],
    metaDescription: 'تحميل رواية أرض زيكولا لعمرو عبد الحميد PDF.'
  },
  {
    id: 'alchemist',
    title: 'الخيميائي',
    author: 'باولو كويلو',
    shortDescription: 'رواية ملهمة عن راعٍ يتبع أحلامه ليصل إلى كنوز الأهرامات ويكتشف أسطورته الشخصية.',
    description: 'رواية "الخيميائي" لباولو كويلو تتبع القصة الشاب "سانتياغو" الذي يحلم بالكنز في رحلة ملهمة.',
    coverImage: 'https://images.unsplash.com/photo-1521119907119-619721df734d?auto=format&fit=crop&q=80&w=400&h=600',
    downloadUrl: SAMPLE_PDF,
    category: 'روايات',
    views: 92000,
    downloads: 48000,
    trending: true,
    price: 'مجاني',
    format: 'PDF',
    pagesCount: 167,
    rating: 4.8,
    ratingCount: 150000,
    seoKeywords: ['الخيميائي', 'باولو كويلو'],
    metaDescription: 'تحميل رواية الخيميائي لباولو كويلو PDF.'
  },
  {
    id: 'power-of-habit-charles',
    title: 'قوة العادة (The Power of Habit)',
    author: 'تشارلز دوهيج',
    shortDescription: 'لماذا نفعل ما نفعل في الحياة والعمل؟ اكتشف الحلقة العلمية لتغيير أي عادة.',
    description: 'في كتاب "قوة العادة"، يشرح تشارلز دوهيج مفهوم "حلقة العادة" المكونة من (الإشارة، الروتين، والمكافأة).',
    coverImage: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&q=80&w=400&h=600',
    downloadUrl: SAMPLE_PDF,
    category: 'علم نفس',
    views: 9800,
    downloads: 3200,
    trending: false,
    price: 'مجاني',
    format: 'PDF',
    pagesCount: 371,
    rating: 4.6,
    ratingCount: 12000,
    seoKeywords: ['قوة العادة', 'تشارلز دوهيج'],
    metaDescription: 'تحميل كتاب قوة العادة PDF.'
  }
];

export const CATEGORIES = [
  'تطوير الذات',
  'روايات',
  'علم نفس',
  'إدارة أعمال',
  'تاريخ',
  'تكنولوجيا',
  'أدب'
];
